import certifi as certifi
import bson
from pymongo import MongoClient
from werkzeug.security import generate_password_hash
import os
import configparser
from datetime import datetime

config = configparser.ConfigParser()
config.read(os.path.abspath(os.path.join(".ini")))

# DB_URI = config['PROD']['PIALARA_DB_URI']
# DB_NAME = config['PROD']['PIALARA_DB_NAME']
DB_URI = config['LOCAL']['PIALARA_DB_URI']
DB_NAME = config['LOCAL']['PIALARA_DB_NAME']

db = MongoClient(
    DB_URI,
    maxPoolSize = 50,
    timeoutMS = 2500,
    ssl=False
)[DB_NAME]

sylabus = [
    {
        "_id": bson.objectid.ObjectId("637a078e8659dd172e6afaf5"),
        "texto": "Esto es una prueba",
        "creador": {
            "id": bson.objectid.ObjectId("6379fc6871880707a2c89537"),
            "nombre": "Rocio",
            "rol": "admin"
        },
        "tags": [
            "dislalia",
            "paralisis facial",
            "futbol",
            "madrid"
        ],
        "audios": [
            {
                "id": bson.objectid.ObjectId("637a08118659dd172e6afafa")
            },
            {
                "id": bson.objectid.ObjectId("637a08208659dd172e6afafb")
            },
            {
                "id": bson.objectid.ObjectId("637a08388659dd172e6afafc")
            }
        ],
        "fecha_creacion": datetime.today()
    },

    {
        "_id": bson.objectid.ObjectId("638348e9b3ba0b56509dfa1b"),
        "texto": "Esto es una prueba 2",
        "creador": {
            "id": bson.objectid.ObjectId("637fd98b2950843403bd5d8a"),
            "nombre": "Mario",
            "rol": "cliente"
        },
        "tags": [
            "dislalia",
            "paralisis facial",
            "futbol",
            "madrid"
        ],
        "audios": [
            {
                "id": bson.objectid.ObjectId("6379ff018659dd172e6afadc"),

            }
        ],
        "fecha_creacion": datetime.today()
    },
    {"texto": "Corrí la maratón en menos de tres horas.", "tags": ["deporte"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Me gusta jugar al fútbol los fines de semana.", "tags": ["deporte"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Entreno con mi entrenador personal todas las mañanas.", "tags": ["deporte"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "El equipo de básquet ganó la final del campeonato.", "tags": ["deporte"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Me encanta nadar en el mar durante el verano.", "tags": ["deporte"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Fui a ver el partido de tenis en Wimbledon.", "tags": ["deporte"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Soy un gran fanático del boxeo.", "tags": ["deporte"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Entreno en el gimnasio todos los días.", "tags": ["deporte"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Mi deporte favorito es el esquí acuático.", "tags": ["deporte"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "El equipo de rugby se entrena muy duro para la temporada.", "tags": ["deporte"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "El atletismo es uno de los deportes más antiguos del mundo.", "tags": ["deporte"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Mi hijo está en la escuela secundaria y juega al básquetbol.", "tags": ["deporte"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "El golf es un deporte muy popular entre los ejecutivos.", "tags": ["deporte"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Me encanta ver partidos de fútbol en la tele con mis amigos.", "tags": ["deporte"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "El equipo de natación ganó el campeonato estatal este año.", "tags": ["deporte"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Jugamos al vóley en la playa todos los veranos.", "tags": ["deporte"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Mi hermano es un gran fanático del fútbol americano.", "tags": ["deporte"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Me gusta ir al parque y jugar al baloncesto con mis amigos.", "tags": ["deporte"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "El equipo de atletismo de mi escuela ganó el campeonato regional este año.", "tags": ["deporte"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Me encanta patinar en el hielo en invierno.", "tags": ["deporte"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "El deporte de la lucha es muy popular en algunos países.", "tags": ["deporte"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Mi hija está en la escuela secundaria y juega al vóley.", "tags": ["deporte"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "El equipo de remo entrena en el río todas las mañanas.", "tags": ["deporte"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Me gusta ir al parque y jugar al frisbee con mi perro.", "tags": ["deporte"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "El deporte de la equitación es muy popular entre las mujeres.", "tags": ["deporte"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "El equipo de tenis de mi escuela ganó el campeonato estatal este año.", "tags": ["deporte"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Me encanta ver partidos de básquetbol en la tele con mi familia.", "tags": ["deporte"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "El deporte del ciclismo es muy popular en algunos países europeos.", "tags": ["deporte"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Mi hermano juega al golf en un equipo de la escuela secundaria.", "tags": ["deporte"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Me encanta ir al parque y jugar al fútbol con mis amigos en verano.", "tags": ["deporte"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Me encanta ir al gimnasio y levantar pesas.", "tags": ["deporte"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "El equipo de básquetbol de mi escuela ganó la final del campeonato estatal.", "tags": ["deporte"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Juego al tenis con mi tía todos los fines de semana.", "tags": ["deporte"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "El deporte del atletismo incluye carreras, saltos y lanzamientos.", "tags": ["deporte"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Mi abuelo juega al golf todos los sábados por la mañana.", "tags": ["deporte"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Me encanta ir a la piscina y nadar laps todas las mañanas.", "tags": ["deporte"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "El equipo de rugby de mi escuela se entrena muy duro para la temporada.", "tags": ["deporte"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "El deporte del boxeo es uno de los más antiguos del mundo.", "tags": ["deporte"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Me encanta ver partidos de fútbol en la tele con mis amigos los fines de semana.", "tags": ["deporte"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "El equipo de natación de mi escuela ganó el campeonato estatal este año.", "tags": ["deporte"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Me encanta jugar al vóley en la playa con mis amigos en verano.", "tags": ["deporte"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Mi hermano es un gran fanático del fútbol americano y juega en un equipo de la escuela secundaria.",
     "tags": ["deporte"], "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Me gusta ir al parque y jugar al baloncesto con mis amigos los fines de semana.", "tags": ["deporte"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "El equipo de atletismo de mi escuela ganó el campeonato regional este año.", "tags": ["deporte"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Me encanta patinar en el hielo en invierno y jugar al hockey sobre hielo en el lago con mis amigos.",
     "tags": ["deporte"], "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Me encanta cocinar platos tradicionales de mi país.", "tags": ["comida"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Me gusta ir a restaurantes y probar nuevas recetas.", "tags": ["comida"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "A mi familia le encanta hacer barbacoas en el jardín los fines de semana.", "tags": ["comida"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Me encanta ir a la verdulería y comprar frutas y verduras frescas.", "tags": ["comida"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Mi abuela siempre me enseña a preparar platos tradicionales de nuestra familia.", "tags": ["comida"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Me gusta ir a la panadería y comprar pan recién horneado.", "tags": ["comida"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "A mi esposo le encanta cocinar y siempre está buscando nuevas recetas para probar.", "tags": ["comida"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Me encanta ir a mercados locales y probar diferentes alimentos.", "tags": ["comida"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Mi hija es una gran fanática de los dulces y le encanta ir a la pastelería.", "tags": ["comida"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Me encanta ir a la carnicería y comprar carne fresca para cocinar.", "tags": ["comida"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "A mi esposa le encanta ir a la pescadería y comprar pescado fresco para cocinar.", "tags": ["comida"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Me encanta ir a la frutería y comprar frutas exóticas para probar.", "tags": ["comida"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Mi hijo es un gran fanático de los helados y le encanta ir a la heladería en verano.",
     "tags": ["comida"], "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Me encanta cocinar platos vegetarianos y probar nuevas recetas.", "tags": ["comida"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "A mi familia le encanta ir a restaurantes y probar platos de diferentes países.", "tags": ["comida"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Me encanta probar diferentes tipos de queso en el mercado local.", "tags": ["comida"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Me gusta ir a la carnicería y comprar carne de alta calidad para cocinar.", "tags": ["comida"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "A mi esposa le encanta ir a la panadería y comprar diferentes tipos de panes artesanales.",
     "tags": ["comida"], "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Me encanta ir a la verdulería y comprar ingredientes frescos para hacer sopas y ensaladas.",
     "tags": ["comida"], "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {
        "texto": "Mi hija es una gran fanática de los postres y le encanta ir a la pastelería y probar diferentes pasteles y galletas.",
        "tags": ["comida"], "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
        "fecha_creacion": datetime.today()},
    {"texto": "Me encanta probar diferentes tipos de vino y hacer degustaciones de vino en casa con amigos.",
     "tags": ["comida"], "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {
        "texto": "A mi esposo le encanta cocinar platos exóticos y siempre está buscando nuevas especias y ingredientes para probar.",
        "tags": ["comida"], "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
        "fecha_creacion": datetime.today()},
    {"texto": "Me encanta ir a mercados locales y probar diferentes alimentos típicos de la región.",
     "tags": ["comida"], "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Mi hijo es un gran fanático de los helados y le encanta probar diferentes sabores en la heladería.",
     "tags": ["comida"], "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Me encanta cocinar platos veganos y probar nuevas recetas y ingredientes.", "tags": ["comida"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "A mi familia le encanta ir a restaurantes y probar platos de diferentes culturas culinarias.",
     "tags": ["comida"], "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Me encanta probar diferentes tipos de aceite de oliva y utilizarlos en mis recetas.", "tags": ["comida"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Me gusta ir a la carnicería y comprar diferentes cortes de carne para cocinar en casa.",
     "tags": ["comida"], "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "A mi esposa le encanta ir a la panadería y comprar diferentes tipos de panes hechos a mano.",
     "tags": ["comida"], "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Me encanta ir a la verdulería y comprar verduras orgánicas y utilizarlas en mis recetas.",
     "tags": ["comida"], "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Me encanta ir al mercado local y probar diferentes tipos de queso artesanal.", "tags": ["comida"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Me gusta comprar carne de alta calidad en la carnicería y utilizarla en mis recetas favoritas.",
     "tags": ["comida"], "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {
        "texto": "A mi esposa le encanta ir a la panadería y comprar diferentes tipos de panes caseros y probarlos con diferentes mantequillas y mermeladas.",
        "tags": ["comida"], "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
        "fecha_creacion": datetime.today()},
    {"texto": "Me encanta ir a la verdulería y comprar frutas y verduras de temporada y utilizarlas en mis recetas.",
     "tags": ["comida"], "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {
        "texto": "Mi hija es una gran fanática de los postres y le encanta ir a la pastelería y probar diferentes tartas y pasteles caseros.",
        "tags": ["comida"], "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
        "fecha_creacion": datetime.today()},
    {
        "texto": "Me encanta probar diferentes marcas y variedades de vino y hacer degustaciones en casa con amigos y familiares.",
        "tags": ["comida"], "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
        "fecha_creacion": datetime.today()},
    {
        "texto": "A mi esposo le encanta cocinar platos exóticos y siempre está buscando nuevas especias y ingredientes para añadir a sus recetas.",
        "tags": ["comida"], "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
        "fecha_creacion": datetime.today()},
    {
        "texto": "Me encanta ir a mercados locales y probar diferentes alimentos típicos de la región y aprender sobre sus tradiciones culinarias.",
        "tags": ["comida"], "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
        "fecha_creacion": datetime.today()},
    {
        "texto": "Mi hijo es un gran fanático de los helados y le encanta probar diferentes sabores y marcas en la heladería.",
        "tags": ["comida"], "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
        "fecha_creacion": datetime.today()},
    {"texto": "Me encanta cocinar platos vegetarianos y veganos y probar nuevas recetas y ingredientes saludables.",
     "tags": ["comida"], "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {
        "texto": "A mi familia le encanta ir a restaurantes y probar platos de diferentes culturas culinarias y aprender sobre sus tradiciones y técnicas de cocina.",
        "tags": ["comida"], "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
        "fecha_creacion": datetime.today()},
    {
        "texto": "Me encanta probar diferentes aceites de oliva y utilizarlos en mis recetas para darle un sabor y aroma únicos.",
        "tags": ["comida"], "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
        "fecha_creacion": datetime.today()},
    {
        "texto": "Me gusta ir a la carnicería y comprar diferentes cortes de carne y aprender a cocinar diferentes platos con ellos.",
        "tags": ["comida"], "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
        "fecha_creacion": datetime.today()},
    {
        "texto": "A mi esposa le encanta ir a la panadería y comprar diferentes tipos de panes hechos a mano y probarlos con diferentes salsas y quesos.",
        "tags": ["comida"], "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
        "fecha_creacion": datetime.today()},
    {
        "texto": "Me encanta ir a la verdulería y comprar verduras orgánicas y utilizarlas en mis recetas para asegurarme de que estoy comiendo alimentos saludables y nutritivos.",
        "tags": ["comida"], "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
        "fecha_creacion": datetime.today()},
    {"texto": "Ordenador portátil con pantalla táctil", "tags": ["tecnología"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Sistema de seguridad de cámaras de vigilancia", "tags": ["tecnología"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Smartphone con sistema operativo Android", "tags": ["tecnología"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Impresora 3D para fabricar objetos", "tags": ["tecnología"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Tableta con conectividad Wi-Fi y Bluetooth", "tags": ["tecnología"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Software de edición de video profesional", "tags": ["tecnología"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Control de voz para hogar inteligente", "tags": ["tecnología"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Almacenamiento en nube para guardar archivos", "tags": ["tecnología"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Robot de limpieza de pisos y ventanas", "tags": ["tecnología"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Dispositivo de rastreo GPS para coches", "tags": ["tecnología"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Cargador inalámbrico para teléfonos móviles", "tags": ["tecnología"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Sistema de audio envolvente para hogar", "tags": ["tecnología"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Consola de juegos con realidad virtual", "tags": ["tecnología"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Sistema de climatización inteligente para hogar", "tags": ["tecnología"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Sistema de entretenimiento en coche con pantalla táctil", "tags": ["tecnología"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Reproductor de música digital con altavoces integrados", "tags": ["tecnología"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Cámara deportiva con estabilizador de imagen", "tags": ["tecnología"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Sistema de control de acceso con lectura de huellas dactilares", "tags": ["tecnología"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Monitor de salud con seguimiento de actividad física", "tags": ["tecnología"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Altavoz inteligente con asistente de voz", "tags": ["tecnología"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Termostato inteligente para control de temperatura en hogar", "tags": ["tecnología"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Pantalla de proyección con tecnología de retroalimentación táctil", "tags": ["tecnología"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Software de diseño gráfico para profesionales", "tags": ["tecnología"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Computadora de escritorio con procesador de última generación", "tags": ["tecnología"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Cámara de vigilancia con detección de movimiento y alerta", "tags": ["tecnología"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Máquina de corte láser para trabajos de precisión", "tags": ["tecnología"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Sistema de carga inalámbrica para dispositivos móviles", "tags": ["tecnología"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Sistema de audio portátil con conectividad Bluetooth", "tags": ["tecnología"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Control de juego inalámbrico para consolas de videojuegos", "tags": ["tecnología"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Software de edición de fotos y vídeos para móviles", "tags": ["tecnología"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Reloj inteligente con seguimiento de sueño y actividad física", "tags": ["tecnología"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Dispositivo de rastreo para localizar objetos perdidos", "tags": ["tecnología"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Sistema de vigilancia para bebés con cámaras y monitores de audio", "tags": ["tecnología"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Tarjeta de expansión de memoria para ordenador portátil", "tags": ["tecnología"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Sistema de iluminación inteligente para hogar", "tags": ["tecnología"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Software de gestión de proyectos para empresas", "tags": ["tecnología"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Pantalla táctil para presentaciones y conferencias", "tags": ["tecnología"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Dispositivo de seguridad para proteger la privacidad en línea", "tags": ["tecnología"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Sistema de carga rápida para teléfonos móviles", "tags": ["tecnología"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Máquina de coser con tecnología de puntada automática", "tags": ["tecnología"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Cepillo de dientes inteligente con seguimiento de limpieza", "tags": ["tecnología"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Software de análisis de datos para empresas", "tags": ["tecnología"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Sistema de sonido envolvente para cine en casa", "tags": ["tecnología"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Máquina de hacer café con sistema de preparación automática", "tags": ["tecnología"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Altavoz inteligente con asistente de voz y pantalla táctil", "tags": ["tecnología"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Explorar nuevos destinos turísticos", "tags": ["viajes"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Recorrer paisajes exóticos en el extranjero", "tags": ["viajes"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Descubrir la cultura local en otras ciudades", "tags": ["viajes"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Hacer una aventura en un lugar desconocido", "tags": ["viajes"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Disfrutar del paisaje mientras se viaja en tren", "tags": ["viajes"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Pasar tiempo en la playa en un lugar tropical", "tags": ["viajes"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Experimentar diferentes formas de transporte en el extranjero", "tags": ["viajes"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Degustar la comida típica de otras regiones", "tags": ["viajes"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Visitar lugares históricos y culturales en el mundo", "tags": ["viajes"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Conocer a personas de diferentes países y culturas", "tags": ["viajes"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Hacer senderismo en una naturaleza salvaje", "tags": ["viajes"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Tomar un crucero por el mar", "tags": ["viajes"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Alojarse en un hotel con encanto en el extranjero", "tags": ["viajes"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Participar en actividades al aire libre en otro lugar", "tags": ["viajes"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Visitar museos y galerías en otras ciudades", "tags": ["viajes"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Disfrutar de la vida nocturna en una ciudad extranjera", "tags": ["viajes"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Hacer compras en un mercado local en el extranjero", "tags": ["viajes"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Disfrutar de una cena en un restaurante típico del lugar", "tags": ["viajes"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Tener una experiencia de intercambio cultural", "tags": ["viajes"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Aprender un nuevo idioma durante el viaje", "tags": ["viajes"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Pasar tiempo en la montaña en un lugar de esquí", "tags": ["viajes"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Realizar un safari en la naturaleza salvaje", "tags": ["viajes"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Disfrutar de una escapada de fin de semana en el campo", "tags": ["viajes"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Visitar una fábrica local en el extranjero", "tags": ["viajes"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Tener una experiencia de voluntariado en otro país", "tags": ["viajes"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Disfrutar de una cena en un barco flotante", "tags": ["viajes"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Visitar una reserva natural en otro lugar", "tags": ["viajes"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Pasar tiempo en la playa en un lugar menos conocido", "tags": ["viajes"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Experimentar la vida en una granja en el extranjero", "tags": ["viajes"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Disfrutar de una escapada de fin de semana en la ciudad", "tags": ["viajes"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Visitar un zoológico en otro lugar", "tags": ["viajes"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Realizar un recorrido en bicicleta por la naturaleza", "tags": ["viajes"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Visitar un parque de atracciones en otro lugar", "tags": ["viajes"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Participar en una caminata por la naturaleza", "tags": ["viajes"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Disfrutar de una escapada de fin de semana en la playa", "tags": ["viajes"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Visitar un jardín botánico en otro lugar", "tags": ["viajes"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Participar en actividades acuáticas en otro lugar", "tags": ["viajes"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Visitar una granja de animales en otro lugar", "tags": ["viajes"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Experimentar la vida en una aldea en el extranjero", "tags": ["viajes"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Disfrutar de una escapada de fin de semana en la montaña", "tags": ["viajes"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Visitar un parque nacional en otro lugar", "tags": ["viajes"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Realizar un recorrido en barco por el río o el mar", "tags": ["viajes"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Participar en una caminata por la selva en otro lugar", "tags": ["viajes"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Disfrutar de una escapada de fin de semana en la ciudad grande", "tags": ["viajes"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Participar en una actividad de senderismo por el campo", "tags": ["viajes"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Automóvil de cuatro ruedas", "tags": ["vehículo"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Vehículo de motor a combustión", "tags": ["vehículo"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Automóvil deportivo de lujo", "tags": ["vehículo"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Camión de carga grande", "tags": ["vehículo"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Sedán familiar con espacio de almacenamiento", "tags": ["vehículo"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Todoterreno para conducir off-road", "tags": ["vehículo"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Convertible con capota plegable", "tags": ["vehículo"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Motocicleta de dos ruedas", "tags": ["vehículo"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Autocaravana para viajar en familia", "tags": ["vehículo"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Furgón de reparto pequeño", "tags": ["vehículo"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Monovolumen con asientos extraíbles", "tags": ["vehículo"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Autocar de lujo con aire acondicionado", "tags": ["vehículo"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Camioneta con tracción en las cuatro ruedas", "tags": ["vehículo"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Scooter eléctrico para la ciudad", "tags": ["vehículo"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Vehículo híbrido que combina gasolina y electricidad", "tags": ["vehículo"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Microbús con capacidad para varios pasajeros", "tags": ["vehículo"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Coche eléctrico sin emisiones de gases", "tags": ["vehículo"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Autocaravana con cocina y cama incorporadas", "tags": ["vehículo"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Furgón de mudanzas grande para trasladar muebles", "tags": ["vehículo"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Tractor de granja con remolque acoplado", "tags": ["vehículo"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Motocicleta de carreras con motor de alta potencia", "tags": ["vehículo"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Monovolumen con sistema de navegación integrado", "tags": ["vehículo"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Automóvil clásico de colección", "tags": ["vehículo"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Vehículo todoterreno con suspensión reforzada", "tags": ["vehículo"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Autocar con asientos reclinables y enfriadores de bebidas", "tags": ["vehículo"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Camioneta con remolque acoplado para transportar herramientas", "tags": ["vehículo"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Scooter de alta velocidad para carreteras", "tags": ["vehículo"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Autocaravana con sistema de calefacción y aire acondicionado", "tags": ["vehículo"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Furgón de reparto con cámara trasera de visión trasera", "tags": ["vehículo"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Tractor con remolque acoplado para el transporte de alimentos", "tags": ["vehículo"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Motocicleta de trial para conducir por terrenos accidentados", "tags": ["vehículo"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Monovolumen con sistema de entretenimiento integrado", "tags": ["vehículo"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Automóvil híbrido con autonomía extendida", "tags": ["vehículo"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Vehículo todoterreno con winch eléctrico", "tags": ["vehículo"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Autocar con sistema de climatización de alta tecnología", "tags": ["vehículo"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Camioneta con equipo de audio de alta calidad", "tags": ["vehículo"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Scooter eléctrico con pantalla táctil y conectividad Bluetooth", "tags": ["vehículo"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Autocaravana con sistema de purificación del aire", "tags": ["vehículo"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Furgón de mudanzas con plataforma hidráulica", "tags": ["vehículo"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Tractor con cabina cerrada para proteger al conductor del clima", "tags": ["vehículo"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Motocicleta de cross para competiciones off-road", "tags": ["vehículo"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Monovolumen con sistema de carga inalámbrico para dispositivos móviles", "tags": ["vehículo"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Automóvil eléctrico con cargador rápido", "tags": ["vehículo"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Camión de bomberos con sistema de extinción de incendios", "tags": ["vehículo"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Autocar con baño y cocina para largos viajes.", "tags": ["vehículo"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "El rock es mi género favorito", "tags": ["música"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Los conciertos en vivo son increíbles", "tags": ["música"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "El jazz tiene una gran historia", "tags": ["música"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Aprendí a tocar la guitarra a los 12 años", "tags": ["música"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "El hip hop es una forma de arte", "tags": ["música"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "La música clásica es hermosa y refinada", "tags": ["música"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "El blues tiene una gran influencia en muchos géneros", "tags": ["música"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "El reggae es una forma de vida", "tags": ["música"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Los sintetizadores son herramientas increíbles en la música electrónica", "tags": ["música"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Los festivales de música son una gran oportunidad para descubrir nuevos artistas", "tags": ["música"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "La música folklórica es una forma de preservar las tradiciones culturales", "tags": ["música"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "La música country es una parte importante de la cultura estadounidense", "tags": ["música"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Los ritmos latinos son muy alegres y bailables", "tags": ["música"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "La música pop es muy popular en todo el mundo", "tags": ["música"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Los artistas de música indie tienen un estilo único y auténtico", "tags": ["música"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Los coros son una parte importante de muchas formas de música", "tags": ["música"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Los arreglos musicales pueden hacer que una canción suene completamente diferente", "tags": ["música"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "El metal es un género muy intenso y poderoso", "tags": ["música"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "La música ambiental puede ser muy relajante", "tags": ["música"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "La música experimental es muy innovadora y creativa", "tags": ["música"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Los sonidos de los instrumentos tradicionales son muy auténticos", "tags": ["música"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Los DJ's son una parte importante de la música electrónica", "tags": ["música"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Los grupos de música en vivo tienen una energía increíble", "tags": ["música"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "La música de baile es muy divertida y alegre", "tags": ["música"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Los teclados son una herramienta esencial en muchos géneros de música", "tags": ["música"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "El rap es una forma de arte que utiliza el lenguaje", "tags": ["música"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Los solos de guitarra son una parte importante de muchas canciones de rock", "tags": ["música"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "La música sinfónica es muy impresionante y épica", "tags": ["música"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Los baterías son una parte esencial de muchos grupos de música", "tags": ["música"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "La música de cámara es muy íntima y refinada", "tags": ["música"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Los sintetizadores pueden crear una gran variedad de sonidos", "tags": ["música"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Los artistas de música indie tienen una gran libertad creativa", "tags": ["música"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "La música de películas puede ser muy emotiva y poderosa", "tags": ["música"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Los arreglos orquestales pueden hacer que una canción suene épica", "tags": ["música"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "La música tradicional de diferentes países es muy interesante", "tags": ["música"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Los bajos son una parte importante de muchos géneros de música", "tags": ["música"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Los acordes de piano pueden ser muy emotivos y evocadores", "tags": ["música"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "La música de videojuegos a menudo tiene una gran energía y emoción", "tags": ["música"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Los instrumentos de viento son una parte importante de muchas orquestas", "tags": ["música"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Los artistas de música alternativa tienen una gran creatividad", "tags": ["música"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "La música de baile es una forma de expresión y diversión", "tags": ["música"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Los músicos de sesión son una parte importante de la industria de la música", "tags": ["música"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Los cánticos son una forma de música muy antigua y espiritual", "tags": ["música"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Los arreglos vocales pueden hacer que una canción suene completamente diferente", "tags": ["música"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "La música de cámara es una forma íntima y refinada de disfrutar la música en grupo pequeño",
     "tags": ["música"], "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Utilizo mi dispositivo portátil para comunicarme con amigos y familiares.", "tags": ["teléfono móvil"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Puedo descargar aplicaciones útiles en mi teléfono inteligente.", "tags": ["teléfono móvil"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Mi teléfono inteligente me permite acceder a Internet en cualquier lugar.", "tags": ["teléfono móvil"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Puedo tomar fotos y grabar vídeos con la cámara de mi teléfono.", "tags": ["teléfono móvil"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Mi teléfono tiene una pantalla táctil para interactuar con él.", "tags": ["teléfono móvil"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Puedo escuchar música y ver películas en mi teléfono móvil.", "tags": ["teléfono móvil"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Mi teléfono tiene una batería que dura todo el día.", "tags": ["teléfono móvil"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Puedo enviar mensajes de texto y correos electrónicos desde mi teléfono.", "tags": ["teléfono móvil"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Mi teléfono tiene una función de GPS para navegar por la ciudad.", "tags": ["teléfono móvil"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Puedo realizar llamadas telefónicas a cualquier lugar del mundo con mi teléfono móvil.",
     "tags": ["teléfono móvil"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Mi teléfono inteligente tiene un procesador rápido y una memoria amplia.", "tags": ["teléfono móvil"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Puedo utilizar mi teléfono para pagar mis compras con una aplicación de pago móvil.",
     "tags": ["teléfono móvil"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Mi teléfono tiene una función de bloqueo de pantalla para proteger mi privacidad.",
     "tags": ["teléfono móvil"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Puedo sincronizar mi teléfono con mi ordenador para transferir archivos.", "tags": ["teléfono móvil"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Mi teléfono tiene una función de detección de movimiento para ahorrar batería.",
     "tags": ["teléfono móvil"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Puedo descargar juegos y aplicaciones de entretenimiento en mi teléfono móvil.",
     "tags": ["teléfono móvil"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Mi teléfono tiene una función de asistente de voz para realizar tareas rápidamente.",
     "tags": ["teléfono móvil"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Puedo usar mi teléfono para monitorear mi actividad física y salud.", "tags": ["teléfono móvil"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Mi teléfono tiene una función de modo nocturno para reducir la fatiga visual.",
     "tags": ["teléfono móvil"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Puedo utilizar mi teléfono para ver mis redes sociales y seguir a mis amigos.",
     "tags": ["teléfono móvil"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Mi teléfono tiene una función de búsqueda de dispositivo en caso de pérdida.",
     "tags": ["teléfono móvil"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Puedo descargar aplicaciones de aprendizaje y formación en mi teléfono móvil.",
     "tags": ["teléfono móvil"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Mi teléfono tiene una función de control parental para proteger a mis hijos.",
     "tags": ["teléfono móvil"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Puedo utilizar mi teléfono para escuchar audiolibros y podcasts durante mis desplazamientos.",
     "tags": ["teléfono móvil"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Mi teléfono tiene una función de encriptación de datos para proteger mi privacidad.",
     "tags": ["teléfono móvil"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Mi teléfono tiene una función de control de voz para realizar tareas sin usar mis manos.",
     "tags": ["teléfono móvil"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Puedo usar mi teléfono para hacer videollamadas con amigos y familiares.", "tags": ["teléfono móvil"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Mi teléfono tiene una función de reconocimiento facial para desbloquearlo de forma rápida y segura.",
     "tags": ["teléfono móvil"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Puedo descargar aplicaciones de productividad y organización en mi teléfono móvil.",
     "tags": ["teléfono móvil"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Mi teléfono tiene una función de control de luz para adaptarse a mi entorno.",
     "tags": ["teléfono móvil"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Puedo usar mi teléfono para controlar otros dispositivos en mi hogar.", "tags": ["teléfono móvil"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Mi teléfono tiene una función de cifrado de mensajes para proteger mi privacidad.",
     "tags": ["teléfono móvil"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Puedo descargar aplicaciones de traducción y comunicación en mi teléfono móvil.",
     "tags": ["teléfono móvil"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Mi teléfono tiene una función de búsqueda de imágenes para encontrar fotos similares.",
     "tags": ["teléfono móvil"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Puedo usar mi teléfono para ver programas de televisión y películas en streaming.",
     "tags": ["teléfono móvil"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Mi teléfono tiene una función de notificaciones para mantenerme al tanto de lo que sucede.",
     "tags": ["teléfono móvil"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Puedo descargar aplicaciones de compras y entrega a domicilio en mi teléfono móvil.",
     "tags": ["teléfono móvil"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Mi teléfono tiene una función de detección de sonrisa para tomar fotos más divertidas.",
     "tags": ["teléfono móvil"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Puedo usar mi teléfono para hacer reservas y comprar entradas para eventos.", "tags": ["teléfono móvil"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Mi teléfono tiene una función de asistente de viajes para planificar mis vacaciones.",
     "tags": ["teléfono móvil"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Puedo descargar aplicaciones de meditación y bienestar en mi teléfono móvil.",
     "tags": ["teléfono móvil"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Mi teléfono tiene una función de detección de rostro para personalizar mis selfies.",
     "tags": ["teléfono móvil"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Puedo usar mi teléfono para hacer seguimiento de mis metas y progreso.", "tags": ["teléfono móvil"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Mi teléfono tiene una función de ahorro de energía para prolongar la vida de la batería.",
     "tags": ["teléfono móvil"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()},
    {"texto": "Puedo usar mi teléfono para controlar mis dispositivos de hogar inteligente", "tags": ["teléfono móvil"],
     "creador": {"id": {"$oid": "639b4085a39c11c0c5121368"}, "nombre": "Mario", "rol": "admin"},
     "fecha_creacion": datetime.today()}
]

sylabusValidator = {
    "$jsonSchema": {
        "required": [
            'texto',
            'creador',
            'fecha_creacion'
        ],
        "properties": {
            "texto": {
                "bsonType": 'string'
            },
            "creador": {
                "bsonType": 'object'
            },
            "tags": {
                "bsonType": 'array'
            },
            "fecha_creacion": {
                "bsonType": 'date'
            }
        }
    }
}

try:
    db.drop_collection("sylabus")
    db.create_collection("sylabus", validator=sylabusValidator)
    db.sylabus.insert_many(sylabus)
except Exception as e:
    print(e)